"""
writeup.py — Automated Writeup / Report Generator
---------------------------------------------------
Reads the current session's command history and generates
a structured Markdown writeup grouped by pentest phase.

Usage inside Hazel:
  hazel> writeup          → print to terminal
  hazel> writeup save     → save to writeup_<date>.md
"""

import os
from datetime import datetime

GREEN  = "\033[92m"
CYAN   = "\033[96m"
BOLD   = "\033[1m"
DIM    = "\033[2m"
YELLOW = "\033[93m"
RESET  = "\033[0m"

# Maps tool names → pentest phase
PHASE_MAP = {
    "Reconnaissance": {
        "nmap", "ping", "whois", "dig", "nslookup", "traceroute",
        "masscan", "arp-scan", "netdiscover"
    },
    "Enumeration": {
        "gobuster", "ffuf", "dirb", "dirbuster", "nikto", "wfuzz",
        "enum4linux", "smbclient", "smbmap", "ldapsearch", "rpcclient",
        "snmpwalk", "wpscan", "crackmapexec"
    },
    "Exploitation": {
        "sqlmap", "metasploit", "msfconsole", "msfvenom", "hydra",
        "john", "hashcat", "nc", "netcat", "python", "python3",
        "php", "ruby", "perl"
    },
    "Post-Exploitation": {
        "ssh", "scp", "curl", "wget", "socat", "chisel",
        "mimikatz", "bloodhound", "linpeas", "winpeas"
    }
}


def _classify_phase(tool: str) -> str:
    """Return which pentest phase a tool belongs to."""
    tool_lower = (tool or "").lower()
    for phase, tools in PHASE_MAP.items():
        if tool_lower in tools:
            return phase
    return "General"


def _group_by_phase(commands: list) -> dict:
    """Group command dicts by pentest phase, skipping blocked commands."""
    groups = {}
    for cmd in commands:
        if cmd.get("was_blocked"):
            continue
        phase = _classify_phase(cmd.get("tool", ""))
        groups.setdefault(phase, []).append(cmd)
    return groups


def _phase_section(phase: str, commands: list) -> str:
    """Render one phase as a Markdown section."""
    lines = [f"\n## {phase}\n"]
    for cmd in commands:
        ts = cmd.get("timestamp", "")
        try:
            dt = datetime.fromisoformat(ts)
            time_str = dt.strftime("%H:%M:%S")
        except (ValueError, TypeError):
            time_str = ts

        lines.append(f"**[{time_str}]** `{cmd['command']}`\n")

        snippet = cmd.get("output_snippet", "")
        if snippet:
            snippet_lines = snippet.strip().splitlines()[:3]
            lines.append("```\n" + "\n".join(snippet_lines) + "\n```\n")

    return "\n".join(lines)


def generate_writeup(session_id: str, commands: list, target: str = "Unknown") -> str:
    """
    Build a full Markdown writeup from session commands.

    Args:
        session_id: Current session UUID.
        commands:   List of command dicts from history module.
        target:     Optional target IP/name for report header.

    Returns:
        Markdown string ready to display or save.
    """
    if not commands:
        return "# Hazel Writeup\n\n_No commands recorded in this session._\n"

    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = [
        "# Hazel CLI — Session Writeup",
        "",
        "| Field     | Value |",
        "|-----------|-------|",
        f"| Target    | `{target}` |",
        f"| Session   | `{session_id}` |",
        f"| Generated | {now} |",
        f"| Commands  | {len(commands)} |",
        "",
        "---",
        "",
        "## Summary",
        "",
        "This writeup was automatically generated by **Hazel CLI**.",
        "Commands are grouped by pentest phase.",
        "",
    ]

    grouped = _group_by_phase(commands)
    phase_order = [
        "Reconnaissance", "Enumeration", "Exploitation",
        "Post-Exploitation", "General"
    ]

    for phase in phase_order:
        if phase in grouped:
            lines.append(_phase_section(phase, grouped[phase]))

    lines.append("\n---\n\n## Appendix — Full Command Log\n")
    for cmd in commands:
        blocked = " *(blocked)*" if cmd.get("was_blocked") else ""
        lines.append(f"- `{cmd['command']}`{blocked}")

    return "\n".join(lines)


def print_writeup(session_id: str, commands: list, target: str = "Unknown"):
    """Generate and pretty-print the writeup to the terminal."""
    writeup = generate_writeup(session_id, commands, target)

    print()
    print(f"{GREEN}{BOLD}{'━' * 55}{RESET}")
    print(f"{GREEN}{BOLD}  📝  HAZEL WRITEUP — Session {session_id[:8]}...{RESET}")
    print(f"{GREEN}{BOLD}{'━' * 55}{RESET}")
    print()

    for line in writeup.splitlines():
        if line.startswith("# "):
            print(f"{GREEN}{BOLD}{line[2:]}{RESET}")
        elif line.startswith("## "):
            print(f"\n{CYAN}{BOLD}{line[3:]}{RESET}")
            print(f"{CYAN}{'─' * 40}{RESET}")
        elif line.startswith("**["):
            print(f"  {BOLD}{line}{RESET}")
        elif line.startswith("- ") or line.startswith("```") or line.startswith("|"):
            print(f"  {DIM}{line}{RESET}")
        else:
            print(f"  {line}")

    print()


def save_writeup(session_id: str, commands: list, target: str = "Unknown"):
    """Save the writeup as a .md file in the current working directory."""
    writeup = generate_writeup(session_id, commands, target)
    date_str = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"writeup_{date_str}_{session_id[:8]}.md"
    filepath = os.path.join(os.getcwd(), filename)

    try:
        with open(filepath, 'w') as f:
            f.write(writeup)
        print(f"\n  {GREEN}{BOLD}✓  Writeup saved to: {filepath}{RESET}\n")
        return filepath
    except IOError as e:
        print(f"\n  {YELLOW}[hazel] Could not save writeup: {e}{RESET}\n")
        return None